### ISSUE TITLE
Subscribe not working on MKR 1000

### ISSUE THREAD

**Issue by rjbaker** [pubnub/arduino#10]
Hi there,

I'm having an issue subscribing and reading events using the subscribe method. It seems to continually loop through the wait/read data method, with an empty response. I used the example subscribe code provided in this repo.

If I change the below lines to simply return client.read(), then the event json is returned, however subsequent messages are incomplete.

https://github.com/pubnub/arduino/blob/master/PubNub.cpp#L169-L176

**Comment by rjbaker** [comment]
I've spoken to PubNub support and this is an known issue. Is there any ETA on a fix? The latest PubNub blog posts detail using this lib with an MKR1000, but only the publish method. Incidentally, this works fine 👍

**Comment by MaxPresman** [comment]
@rjbaker thanks for raising the issue, we are currently investigating and hope to update the thread soon.

**Comment by vveljko** [comment]
The latest commit should fix this and similar issues. Please try it out and let us know if it doesn't work for you.

**Comment by rjbaker** [comment]
Thanks @vveljko I will take a look shortly!

**Comment by rjbaker** [comment]
Can confirm this works! Thanks!
