### ISSUE TITLE
Support for ESP8266

### ISSUE THREAD

**Issue by ztittle** [pubnub/arduino#13]
It would be fantastic if this library was supported on the [ESP8266 ](https://github.com/esp8266/Arduino) microcontroller.  The ESP8266 Arduino environment provides a WiFiClient that is derived from the Arduino's Client class so it shouldn't be a huge effort to support it.

**Comment by vveljko** [comment]
With version 2.0.0 the library supports any HW that has a "driver"/library that is compatible with Arduino de-facto standard interfaces/classes. This should work w/ESP8266, too. Read documentation on how to use your HW of choice.

Let us know if you find any issues with it.
