### ISSUE TITLE
How to make it work with ENC28J60 chip

### ISSUE THREAD

**Issue by Moussawi7** [pubnub/arduino#5]
Dear,
I am trying to use PubNub with ENC28J60 chip, where this chip uses the following library https://github.com/jcw/ethercard .
Does you support this chip?, if yes can you please let me know which files should be modified.
Thank you.

**Comment by geremyCohen** [comment]
@Moussawi7 thanks for your inquiry!  Please contact us at support@pubnub.com so we can learn more about your project and help determine if this this client SDK is best for your project.
